export:
    resource: "@ExportBundle/Resources/config/routing.yml"
    prefix:   /

document:
    resource: "@DocumentBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
